package com.ggar.altair.model;

import com.magc.sensecane.framework.model.database.TableEntity;
import com.magc.sensecane.framework.model.database.annotation.Autogenerated;
import com.magc.sensecane.framework.model.database.annotation.Column;
import com.magc.sensecane.framework.model.database.annotation.PrimaryKey;
import com.magc.sensecane.framework.model.database.annotation.Table;

@Table("urls")
public class Url extends TableEntity<Integer> implements Item {

	@PrimaryKey @Autogenerated @Column("id") private final Integer id;
	@Column("value") private final String value;
	@Column("date_added") private final Long dateAdded;
	
	public Url() {
		this(null, null, null);
	}

	public Url(Integer id, String value, Long dateAdded) {
		super();
		this.id = id;
		this.value = value;
		this.dateAdded = dateAdded;
	}

	public Integer getId() {
		return id;
	}

	public String getValue() {
		return value;
	}

	public Long getDateAdded() {
		return dateAdded;
	}
	
}
